services:
  ai_project_db:
    image: postgres:13
    restart: always
    container_name: ai_project_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - PGDATA=/var/lib/postgresql/data
    user: postgres
    ports:
      - '5432:5432'
    volumes:
      # - ai_project_db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  ai_project_api:
    restart: always
    build:
      context: ./api
      dockerfile: api.Dockerfile
    container_name: ai_project_api
    user: root
    volumes:
      - ./api:/api
      # - ./ssl:/ssl
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python api.py
    ports:
      - '5000:5000'
    depends_on:
      - ai_project_db
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/neo4jpass
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
volumes:
  ai_project_db:
    driver: local
